apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Release.Name }}-service
spec:
  selector:
    app: {{ .Values.Release.Name }}
  ports:
  - name: http
    port: 6000
    targetPort: {{ .Values.container.port }}
  type: ClusterIP
